version: '3'

services:
  
  product-launch-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=DockerCon2017
    networks:
      - app-net

  product-launch-web:
    image: beedemo/modernize-aspnet-web:v1
    ports:
      - "80:80"
    depends_on:
      - product-launch-db
    networks:
      - app-net

networks:
  app-net:
    external: 
     name: nat